trigger:
- master

variables:
  dockerRegistryServiceConnection: '7146df36-32ae-4c47-9a14-dd03529396a3'
  imageRepository: 'barberboss'
  containerRegistry: 'apibarberboss.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: appSettings
  displayName: Downloading appsettings.Production.json file
  inputs:
    secureFile: appsettings.Production.json

- script: |
    cp $(appSettings.secureFilePath) src/BarberBoss.Api/appsettings.Production.json

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)